name: Aydakar CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - uses: actions/checkout@v4
      - name: Notify Discord - Starting Build
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "üöÄ **Aydakar CI** ba≈üladƒ±!"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Notify Discord - Dependencies Installed
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "üì¶ **npm ci** tamamlandƒ±!"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
      - run: npx next telemetry disable
      - run: npm run build --if-present
      - name: Notify Discord - Build Completed
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "‚úÖ **Build i≈ülemi tamamlandƒ±!**"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
      - name: PM2 List
        run: pm2 list
      - name: Change Directory
        run: cd /actions-runner/_work/aydakar/aydakar
      - run: pm2 restart aydakar
      - name: Notify Discord - PM2 Restarted
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "‚ôªÔ∏è **PM2 restart edildi!**"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
