name: Aydakar CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        bun-version: [1.x]

    steps:
      - uses: actions/checkout@v4
      - name: Notify Discord - Starting Build
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{
            "embeds": [{
              "title": "ğŸš€ Aydakar CI BaÅŸladÄ±!",
              "color": 15258703,
              "fields": [
                { "name": "ğŸ‘¤ KullanÄ±cÄ±", "value": "${{ github.actor }}", "inline": true },
                { "name": "ğŸ”— Commit ID", "value": "`${{ github.sha }}`", "inline": true }
              ],
              "thumbnail": { "url": "https://github.com/${{ github.actor }}.png" }
            }]
          }' "${{ secrets.DISCORD_WEBHOOK_URL }}"

      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - name: Notify Discord - Dependencies Installed
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "`${{ github.sha }}`\nğŸ“¦ **bun install** tamamlandÄ±!"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
      - run: bunx --bun next telemetry disable
      - run: bun run build
      - name: Notify Discord - Build Completed
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "`${{ github.sha }}`\nâœ… **Build iÅŸlemi tamamlandÄ±!**"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
      - name: PM2 List
        run: pm2 list
      - name: Change Directory
        run: cd /actions-runner/_work/aydakar/aydakar
      - run: pm2 restart aydakar
      - name: Notify Discord - PM2 Restarted
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "`${{ github.sha }}`\nâ™»ï¸ **PM2 restart edildi!**"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
